name: ci
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check
        if: matrix.os == 'ubuntu-latest'
      - run: deno lint
        if: matrix.os == 'ubuntu-latest'
      - run: deno task cov
      - uses: codecov/codecov-action@v3
